# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9b4cfe8597fbfc9fd5bb17d0050247fe0adb0db9cbbee5ddd8901d42aac7dc807869f08fad7cf4967b14261ae80fd6cd6bc91787aa10a4c11526e1155b81459

test:
  secret_key_base: d70c51f6286671ef10fb0876fc5b5ce9087c79a58719bd998bd4726f9554e4fccfaf4057f07147b59916cc8e55edf162b4784fc9769afc88513fd586544d0443

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
